on:
  push:
  schedule:
  - cron: "17 */12 * * *"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.6.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: "current"
    - name: install rhombus prototype
      run: raco pkg install --batch --auto https://github.com/mflatt/shrubbery-rhombus-0.git
    - name: install Racket compat library
      run: raco pkg install --batch --auto ./rhombus-compat
    - name: install web example
      run: raco pkg install --batch --auto ./rhombus-examples-web
    - name: install sheepdogs example
      run: raco pkg install --batch --auto ./rhombus-examples-sheepdogs
    - name: install kanren example
      run: raco pkg install --batch --auto ./rhombus-examples-kanren
    - name: check dependencies
      run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs rhombus-examples-web rhombus-examples-sheepdogs rhombus-examples-kanren
  test_dynamic_dot_branch:
    runs-on: "ubuntu-latest"
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.6.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: "current"
    - name: install rhombus prototype
      run: raco pkg install --batch --auto https://github.com/samdphillips/shrubbery-rhombus-0.git#racket-class
    - name: install Racket compat library
      run: raco pkg install --batch --auto ./rhombus-compat
    - name: install class interop example
      run: raco pkg install --batch --auto ./rhombus-examples-class-interop
    - name: check dependencies
      run: raco setup --check-pkg-deps --unused-pkg-deps --pkgs rhombus-examples-class-interop
    - name: simple interop test
      run: racket -l- rhombus-examples/class/use.rhm
